#!/bin/sh

# http://wiki.openwrt.org/toh/tp-link/tl-mr3040#hardware_slide_switch_v2

sleep 1
logger "log: $BUTTON -- $ACTION"

if [ $ACTION == "released" ] ; then
    if [ $BUTTON == "BTN_1" ] ; then
        logger "Slider WISP"
        # Not sure what this should do yet
    elif [ $BUTTON == "BTN_0" ] && grep -qe "sw1.*in  lo" /sys/kernel/debug/gpio ; then
        logger "Slider 3G 4G"
        # Gateway mode triggered
        /etc/init.d/firewall enable
        echo "
        set batman-adv.bat0.gw_mode='server'
        set dhcp.mesh_bridge.ignore=0
        set network.lan.proto=dhcp
        set network.bat.proto=static
        set network.bat.ipaddr=IP_ADDRESS
        set network.bat.netmask=255.255.255.0
        commit" \
            | uci batch
        reboot
    fi
elif [ $BUTTON == "BTN_0" ] || [ $BUTTON == "BTN_1" ] ; then
    if grep -qe "sw1.*in  hi" /sys/kernel/debug/gpio ; then
        if grep -qe "sw2.*in  hi" /sys/kernel/debug/gpio ; then
            logger "Slider AP"
            # AP mode triggered
            /etc/init.d/firewall disable
            echo "
            set batman-adv.bat0.gw_mode=client
            set dhcp.mesh_bridge.ignore=1
            set network.lan.proto=static
            set network.lan.ipaddr=192.168.1.1
            set network.lan.netmask=255.255.255.0
            set network.bat.proto=dhcp
            commit" \
                | uci batch
            reboot
        fi
    fi
fi
